import type { Post } from "../types/community";

export const SAMPLE_POSTS: Post[] = [
  {
    id: "1",
    title: "교내 단체메시지 작성기",
    desc: "교직원용 단체 메시지를 자동으로 작성해주는 도구입니다.",
    author: "Social Goodteacher",
    views: 113,
    comments: 18,
    likes: 1,
    category: "교육",
    createdAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "AI! 인스타그램 콘텐츠를 만들어줘 🙌",
    desc: "인스타그램에 적합한 콘텐츠 게시글을 작성해봅니다.",
    author: "정은서",
    views: 33,
    comments: 6,
    likes: 0,
    category: "마케팅",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "댓글의 달글",
    desc: "게시글 내용을 보고 댓글의 답글을 달아봅니다.",
    author: "늘봄 (Neul Bom)",
    views: 45,
    comments: 5,
    likes: 2,
    category: "블로그",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "카피라이팅",
    desc: "카피라이팅하러고 만들었어",
    author: "Gyu-Sang Cho",
    views: 27,
    comments: 5,
    likes: 0,
    category: "마케팅",
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    title: "AI 딱깍 자소서 생성기",
    desc: "딱딱 몇 번의 클릭과 복붙만으로 자소서를 완성해보세요.",
    author: "오쌤(학부모/바이오의공학부)",
    views: 222,
    comments: 11,
    likes: 3,
    category: "학생",
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    title: "어디가 불편하신가요?",
    desc: "몸과 마음이 아프실 때 저에게 물어봐주세요.",
    author: "arthur choi",
    views: 48,
    comments: 4,
    likes: 0,
    category: "법률/일반",
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "7",
    title: "콘텐츠 원고 생성",
    desc: "콘텐츠 원고 만들기",
    author: "SoonHo Jung",
    views: 118,
    comments: 11,
    likes: 1,
    category: "블로그",
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "8",
    title: "운동하게 만들어쥬겠어",
    desc: "운동하게 만들어주겠어",
    author: "Amy Seo",
    views: 23,
    comments: 4,
    likes: 0,
    category: "기타",
    createdAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "9",
    title: "사나운북극곰들이",
    desc: "티스토리에 글을 쓰기 위한 툴입니다.",
    author: "Kaebi",
    views: 22,
    comments: 2,
    likes: 0,
    category: "블로그",
    createdAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
  },
];
