const players = [
  { id: 1, number: 99, name: "류현진" },
  { id: 2, number: 1, name: "문동주" },
  { id: 3, number: 3, name: "안치홍" },
  { id: 4, number: 5, name: "윤대경" },
  { id: 5, number: 7, name: "이도윤" },
  { id: 6, number: 8, name: "노시환" },
  { id: 7, number: 11, name: "엄상백" },
  { id: 8, number: 13, name: "최재훈" },
  { id: 9, number: 15, name: "김기중" },
  { id: 10, number: 20, name: "이재원" },
  { id: 11, number: 22, name: "김민우" },
  { id: 12, number: 25, name: "김태연" },
  { id: 13, number: 26, name: "한승혁" },
  { id: 14, number: 27, name: "장민재" },
  { id: 15, number: 29, name: "황준서" },
  { id: 16, number: 30, name: "배민서" },
  { id: 17, number: 33, name: "정은원" },
  { id: 18, number: 36, name: "장시환" },
  { id: 19, number: 41, name: "최인호" },
  { id: 20, number: 50, name: "이원석" },
  { id: 21, number: 51, name: "박상원" },
  { id: 22, number: 53, name: "채은성" },
  { id: 23, number: 55, name: "이태양" },
  { id: 24, number: 58, name: "김서현" },
  { id: 25, number: 68, name: "조동욱" },
  { id: 26, number: 86, name: "문현빈" },
  { id: 27, number: 95, name: "황영묵" },
  { id: 28, number: 0, name: "루이스 리베라토" },
  { id: 29, number: 12, name: "허관회" },
  { id: 30, number: 2, name: "심우준" },
  { id: 31, number: 10, name: "이진영" },
  { id: 32, number: 9, name: "이상혁" },
];

export default players;
