name: Deploy to GitHub Pages

on:
  # main 브랜치에 push될 때 실행
  push:
    branches: [ main ]
  
  # 수동으로도 실행 가능
  workflow_dispatch:

# GitHub Pages 배포 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 실행 제한 (하나의 배포만 실행)
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 빌드 작업
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './HanwhaIgilShootClient/package-lock.json'

      - name: Install dependencies
        run: |
          cd HanwhaIgilShootClient
          npm ci

      - name: Build
        run: |
          cd HanwhaIgilShootClient
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './HanwhaIgilShootClient/dist'

  # 배포 작업
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
